[package]
name = "set3"
version = "0.1.0"
edition = "2018"

[dependencies]
aes = "0.7.4"
base64 = "0.13.0"
byteorder = "1.4.2"
rand = "0.8.4"
set1 = {path="../set1/"}
set2 = {path="../set2/"}
utils = {path="../utils/"}
