[package]
name = "runner"
version = "0.1.0"
edition = "2018"


[dependencies]
set1 = {path="../set1/"}
set2 = {path="../set2/"}
set3 = {path="../set3/"}
set4 = {path="../set4/"}
set5 = {path="../set5/"}
set6 = {path="../set6/"}
utils = {path="../utils/"}